---

platform: linux

image_resource:
  type: docker-image
  source: 
    repository: nulldriver/cf-cli-resource
 
params:
  API_ENDPOINT: 
  USERNAME: 
  PASSWORD: 
  ORG: 
  SPACE: 
  CF_SUB_COMMAND: 
  COUNT:
  
inputs:
  - name: pcflab

run:
  path: pcflab/start-apps/tasks/cf-deployment.sh

