resource_types:
- name: muntha123
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    #tag: latest-final

resources:
- name: pcflab
  type: git
  source:
    uri: https://github.com/muntha123/pcflab.git
    branch: master
    #username: ((vsts_username))
    #password: ((vsts_token))

jobs:
- name: ((cf-sub-command))-apps
  plan:
  - aggregate:
    - get: pcflab
      trigger: true
  - task: start-apps
    file: pcflab/start-apps/tasks/cf-deployment.yml
    params:
      API_ENDPOINT: ((cf-api))
      USERNAME: ((concourse-automation-client-id))
      PASSWORD: ((concourse-automation-client-secret))
      ORG: ((cf-org))
      SPACE: ((cf-space))
      CF_SUB_COMMAND: ((cf-sub-command))
